apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
  name: mysql-pvc
  namespace: mysql-ns
spec: 
  storageClassName: standard 
  accessModes: 
  - ReadWriteOnce 
  resources: 
    requests: 
      storage: 2Gi
